name: Auto update

on:
  schedule:
    - cron: "7 * * * *"
  workflow_dispatch:
  

jobs:
  update:
    name: Update zen
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check version
        id: version-check
        run: |
          version=$(curl -s https://api.github.com/repos/zen-browser/desktop/releases/latest | jq -r '.tag_name')
          current=$(cat ./flake.nix | grep -oP 'version\s*=\s*"\K[^\"]+')

          if [ "$version" != "$current" ]; then
            echo "newest_version=$version" >> $GITHUB_OUTPUT
          fi

      - uses: DeterminateSystems/nix-installer-action@main
        if: ${{ steps.version-check.outputs.newest_version }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
        if: ${{ steps.version-check.outputs.newest_version }}
      - uses: DeterminateSystems/flake-checker-action@main
        if: ${{ steps.version-check.outputs.newest_version }}

      - name: Update
        if: ${{ steps.version-check.outputs.newest_version }}
        env:
          ZEN_VERSION: ${{ steps.version-check.outputs.newest_version }}
        run: |
          baseUrl="https://github.com/zen-browser/desktop/releases/download/$ZEN_VERSION"

          specificUrl="$baseUrl/zen.linux-specific.tar.bz2"
          specificSha=$(nix-prefetch-url --type sha256 --unpack $specificUrl)

          genericUrl="$baseUrl/zen.linux-generic.tar.bz2"
          genericSha=$(nix-prefetch-url --type sha256 --unpack $genericUrl)

          sed -i "s/version = \".*\"/version = \"$ZEN_VERSION\"/" ./flake.nix
          sed -i "s/specific.sha256 = \".*\"/specific.sha256 = \"sha256:$specificSha\"/" ./flake.nix
          sed -i "s/generic.sha256 = \".*\"/generic.sha256 = \"sha256:$genericSha\"/" ./flake.nix

          nix flake update
          nix build

      - name: Commit changes
        if: ${{ steps.version-check.outputs.newest_version }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update to ${{ steps.version-check.outputs.newest_version }}"
          file_pattern: '*'
